service:
  name: ebs-inspector-lambda
frameworkVersion: =1.40.0
provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'us-east-1'}
  stackName: ebs-inspector-lambda-stack
  profile: ${opt:profile, 'default'}
  memorySize: 256
  logRetentionInDays: 7
  deploymentBucket:
    name: shs-serverless-deployable-${self:provider.region}-${opt:awsAccountNo}
    serverSideEncryption: AES256
  deploymentPrefix: ${opt:deploymentprefix, 'serverless'}
  stackTags:
    BusinessUnit: Platform
    Env: stage
    Name: EBS-Inspector
    Project: Cost-Management-Solution
    Product: SRD
    CreatedBy: GBHOSAL 
  iamRoleStatements:
  - Effect: Allow
    Action:
    - elasticbeanstalk:DescribeEnvironmentResources
    - elasticbeanstalk:DescribeEnvironments
    - autoscaling:DescribeAutoScalingGroups
    - autoscaling:DescribeTags
    - cloudformation:DescribeStacks
    - autoscaling:UpdateAutoScalingGroup
    Resource:
    - '*'
package:
  individually: true
functions:
  FindAllEbEnvironmentsFunction:
    name: find-all-eb-environments
    description: This lambda code will inspect Elastic Beanstalk environments in the account and will suspend the environments if it falls outside of working hours and bring them back up during working hours
    handler: com.ebs.inspector.handlers.FindAllEbEnvironmentsHandler
    memorySize: 512
    timeout: 900
    package:
      artifact: find-all-eb-environments/target/find-all-eb-environments-2.0.0-aws.jar
    environment:
      FUNCTION_NAME: FindAllEbEnvironmentsFunction
      OFF_BUSINESS_HOUR_WINDOW: 18:00-23:59,00:00-00:30
      OFF_BUSINESS_HOUR_TIMEZONE: America/Chicago
      OFF_BUSINESS_DAY_OF_WEEK: SATURDAY,SUNDAY
    events:
      - schedule:
          name: EBS-Inspector-Scheduler-Event
          description: Invokes the EBS Inspector Lambda
          rate: cron(0 0/1 * * ? *)
          enabled: true         